### PR TITLE
SW-3924 CRUD API endpoints for projects

### PR DESCRIPTION
**Pull request by sgrimm**
Define the database schema for projects, including project IDs on accessions,
planting sites, and seedling batches but not including reports.

Add API endpoints under `/api/v1/projects` for basic CRUD operations. Subsequent
changes will add API support for associating projects with other entities.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1299** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1299" target="_blank">Graphite</a> 
    * **PR #1300** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1300" target="_blank">Graphite</a>  👈
      * **PR #1301** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1301" target="_blank">Graphite</a> 
        * **PR #1302** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1302" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1300?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
Straightforward 👍

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1300).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1300) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1300).

**Pull request merged**
