### PR TITLE
SW-2991 Add internal tagging of organizations

### PR DESCRIPTION
**Pull request by sgrimm**
Our internal administrators need to be able to tell the system which
organizations are expected to submit quarterly reports. In addition, we've
gotten a steady stream of requests to run ad-hoc reporting queries on specific
subsets of organizations, or to exclude certain organizations from our
aggregated totals.

To solve both problems, add the concept of "internal tags" to the system.
Internal tags are, as the name suggests, only for internal use; they are not
exposed to end users in any way, and are only visible to super admins.

Define an initial fixed set of internal tags to cover some known use cases:
`Reporter` is for organizations that need to submit reports, `Internal` is for
our own internal projects, and `Testing` is for dummy organizations we use to
test the app.

In addition to these system-defined internal tags, add the ability to define
new ones via the admin UI. The admin UI also allows assigning internal tags to
organizations. These features are only available to super-admin users.

Currently, internal tags aren't used for anything by the system; subsequent
changes will introduce tag-dependent behavior. But analytics queries can
start using them right away.

This new feature uses the term "internal tag" rather than just "tag" because at
various times we have discussed adding a user-facing tagging feature. If we
implement that at some point, we'll want a clear distinction between internal
and user-facing tags.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #982** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/982" target="_blank">Graphite</a> 
    * **PR #983** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/983" target="_blank">Graphite</a> 
      * **PR #985** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/985" target="_blank">Graphite</a> 
        * **PR #986** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/986" target="_blank">Graphite</a> 
          * **PR #988** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/988" target="_blank">Graphite</a>  👈
            * **PR #989** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/989" target="_blank">Graphite</a> 
              * **PR #990** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/990" target="_blank">Graphite</a> 
                * **PR #991** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/991" target="_blank">Graphite</a> 
                  * **PR #992** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/992" target="_blank">Graphite</a> 
                    * **PR #994** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/994" target="_blank">Graphite</a> 
                      * **PR #995** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/995" target="_blank">Graphite</a> 
                        * **PR #996** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/996" target="_blank">Graphite</a> 
                          * **PR #997** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/997" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/988?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #982** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/982" target="_blank">Graphite</a> 
    * **PR #983** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/983" target="_blank">Graphite</a> 
      * **PR #985** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/985" target="_blank">Graphite</a> 
        * **PR #986** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/986" target="_blank">Graphite</a> 
          * **PR #988** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/988" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/988?utm_source=stack-comment).

**Comment by sgrimm** [comment]
This is stacked on the reporting PRs to avoid database migration numbering conflicts. The actual functionality here doesn't rely on the other PRs in the stack.

**Comment by sgrimm** [comment]
Screenshot 2023-02-22 at 9 29 37 AM

Screenshot 2023-02-22 at 9 30 55 AM

**Review by karthikbtf — APPROVED** [review]
Looks great to me!!

**Pull request merged**
