### PR TITLE
SW-1939 Remove isManualState field from AccessionModel

### PR DESCRIPTION
**Pull request by sgrimm**
There are no longer any v1 accessions in the system, so remove the model flag that
indicated whether an accession was v1 or v2.

This doesn't drop the database column; it will be dropped in a subsequent change.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #741** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/741" target="_blank">Graphite</a> 
    * **PR #742** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/742" target="_blank">Graphite</a> 
      * **PR #743** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/743" target="_blank">Graphite</a> 
        * **PR #744** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/744" target="_blank">Graphite</a> 
          * **PR #745** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/745" target="_blank">Graphite</a> 
            * **PR #746** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/746" target="_blank">Graphite</a> 
              * **PR #747** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/747" target="_blank">Graphite</a> 
                * **PR #748** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/748" target="_blank">Graphite</a> 
                  * **PR #749** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/749" target="_blank">Graphite</a> 
                    * **PR #750** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/750" target="_blank">Graphite</a> 
                      * **PR #751** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/751" target="_blank">Graphite</a> 
                        * **PR #752** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/752" target="_blank">Graphite</a> 
                          * **PR #753** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/753" target="_blank">Graphite</a> 
                            * **PR #754** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/754" target="_blank">Graphite</a>  👈
                              * **PR #757** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/757" target="_blank">Graphite</a> 
                                * **PR #758** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/758" target="_blank">Graphite</a> 
                                  * **PR #759** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/759" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/754?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #741** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/741" target="_blank">Graphite</a> 
    * **PR #742** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/742" target="_blank">Graphite</a> 
      * **PR #743** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/743" target="_blank">Graphite</a> 
        * **PR #744** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/744" target="_blank">Graphite</a> 
          * **PR #745** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/745" target="_blank">Graphite</a> 
            * **PR #746** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/746" target="_blank">Graphite</a> 
              * **PR #747** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/747" target="_blank">Graphite</a> 
                * **PR #748** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/748" target="_blank">Graphite</a> 
                  * **PR #749** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/749" target="_blank">Graphite</a> 
                    * **PR #750** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/750" target="_blank">Graphite</a> 
                      * **PR #751** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/751" target="_blank">Graphite</a> 
                        * **PR #752** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/752" target="_blank">Graphite</a> 
                          * **PR #753** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/753" target="_blank">Graphite</a> 
                            * **PR #754** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/754" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/754?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #741** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/741" target="_blank">Graphite</a> 
    * **PR #742** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/742" target="_blank">Graphite</a> 
      * **PR #743** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/743" target="_blank">Graphite</a> 
        * **PR #744** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/744" target="_blank">Graphite</a> 
          * **PR #745** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/745" target="_blank">Graphite</a> 
            * **PR #746** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/746" target="_blank">Graphite</a> 
              * **PR #747** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/747" target="_blank">Graphite</a> 
                * **PR #748** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/748" target="_blank">Graphite</a> 
                  * **PR #749** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/749" target="_blank">Graphite</a> 
                    * **PR #750** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/750" target="_blank">Graphite</a> 
                      * **PR #751** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/751" target="_blank">Graphite</a> 
                        * **PR #752** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/752" target="_blank">Graphite</a> 
                          * **PR #753** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/753" target="_blank">Graphite</a> 
                            * **PR #754** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/754" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/754?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #741** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/741" target="_blank">Graphite</a> 
    * **PR #742** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/742" target="_blank">Graphite</a> 
      * **PR #743** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/743" target="_blank">Graphite</a> 
        * **PR #744** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/744" target="_blank">Graphite</a> 
          * **PR #745** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/745" target="_blank">Graphite</a> 
            * **PR #746** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/746" target="_blank">Graphite</a> 
              * **PR #747** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/747" target="_blank">Graphite</a> 
                * **PR #748** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/748" target="_blank">Graphite</a> 
                  * **PR #749** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/749" target="_blank">Graphite</a> 
                    * **PR #750** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/750" target="_blank">Graphite</a> 
                      * **PR #751** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/751" target="_blank">Graphite</a> 
                        * **PR #752** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/752" target="_blank">Graphite</a> 
                          * **PR #753** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/753" target="_blank">Graphite</a> 
                            * **PR #754** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/754" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/754?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]

**Pull request merged**
