### PR TITLE
SW-3699 API endpoint to fetch observation photos

### PR DESCRIPTION
**Pull request by sgrimm**
Add a GET endpoint to fetch photos of monitoring plots taken during observations.

The file IDs of the photos are already included in the observation results, so
there is no "list photos" endpoint. As with the other photo endpoints in the API,
optional `maxWidth` and `maxHeight` parameters can be included to retrieve
thumbnails.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1193** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1193" target="_blank">Graphite</a> 
    * **PR #1183** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1183" target="_blank">Graphite</a> 
      * **PR #1194** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1194" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1194?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Nice 👍

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1194).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1194) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1194).

**Pull request merged**
