### PR TITLE
SW-3352 MortalityRateInNursery Not Required

### PR DESCRIPTION
**Pull request by charlie-tf**
A change in requirements means that for species in a planting site, the
mortality rate in nursery is no longer required. And the input for this
has been removed on the frontend. To allow a report to be validated,
remove the requirement. We also go through and remove the field from
the model and payloads.

### CODE REVIEW

**Review by sgrimm — APPROVED** [review]
Seems safe enough. If the input is going away, should the field go away entirely, as opposed to just the validation?

**Comment by charlie-tf** [comment]
> Seems safe enough. If the input is going away, should the field go away entirely, as opposed to just the validation?

Good point, I will remove it.

**Review by karthikbtf — APPROVED** [review]
Any related schema changes?

**Comment by charlie-tf** [comment]
> Any related schema changes?

No, if you mean SQL schema changes. The report data is all serialized as json before going into/out of the DB

**Pull request merged**
