### PR TITLE
SW-3394 Deploy using Tailscale instead of bastion

### PR DESCRIPTION
**Pull request by sgrimm**
When deploying to the AWS hosts, connect to the VPC network using Tailscale and
ssh directly to the hosts rather than bouncing through a bastion host.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1083** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1083" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1083?utm_source=stack-comment).

**Comment by sgrimm** [comment]
https://github.com/terraware/terraware-server/actions/runs/5260420438/jobs/9507630468 has a test run where I modified the deploy script to run `ls -l /` instead of actually copying code, to prove that it could successfully ssh to the staging hosts.

**Comment by sgrimm** [comment]
Once this lands and we use it successfully, I'll change the remaining Terraware repos and then we should be able to get rid of the bastion hosts.

**Review by charlie-tf — APPROVED** [review]
Neat!

**Pull request merged**
