### PR TITLE
SW-6370 Updated list users permissions

### PR DESCRIPTION
**Pull request by tommylau523**
Allow contributor to list users. Contributors will be able to view the list of organization users, without the ability to add and edit any of them. This will also fixed some issues with contributors not being able to view batch edit history correctly.

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#2707** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2707?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2707?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by sgrimm** [comment]
What's the goal here? There's no PR description to say why this change is needed, and the Jira task doesn't seem to have anything to do with listing users. Why do we want contributors to be able to list users now, when previously we only allowed managers to do it?

**Comment by tommylau523** [comment]
Updated ticket tracker. 

This is the thread with details:
https://terraformation.atlassian.net/jira/software/c/projects/SW/boards/30?assignee=712020%3A040793d8-76ea-4b4b-9a58-ceb24ff0c771&selectedIssue=SW-6370#:~:text=https%3A//terraformationteam.slack.com/archives/C01VAAP3K0W/p1734376861821589

**Comment by tommylau523** [comment]
Added some descriptions to reflect this.

**Review by sgrimm — APPROVED** [review]
Ah, that Jira task makes much more sense for this!

**Pull request merged**
