### PR TITLE
SW-4232 Add editable observation coordinates

### PR DESCRIPTION
**Pull request by sgrimm**
Observation results for a monitoring plot can now include a list of the GPS
coordinates of the four corners of the plot. These coordinates are optional
and are stored separately from the existing coordinates (photos, recorded plants).
They must be set using a new PUT endpoint.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1410** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1410" target="_blank">Graphite</a> 
    * **PR #1411** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1411" target="_blank">Graphite</a> 
      * **PR #1415** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1415" target="_blank">Graphite</a> 
        * **PR #1416** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1416" target="_blank">Graphite</a>  👈
      * **PR #1412** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1412" target="_blank">Graphite</a> 
        * **PR #1413** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1413" target="_blank">Graphite</a> 
          * **PR #1414** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1414" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1416?utm_source=stack-comment).

**Comment by sgrimm** [comment]
This is stacked on top of the storage location PRs just to keep the database migration numbers consistent, but if this gets approved first, I can renumber the migrations.

**Review by karthikbtf — APPROVED** [review]
Looks good to me 👍 
Guessing this will be used by the mobile app.

**Comment by sgrimm** [comment]
> Guessing this will be used by the mobile app.

It will actually be used by the web app. Use case is when people want to manually enter GPS coordinates other than the ones automatically recorded by the mobile app.

**Comment by sgrimm** [comment]
### Merge activity

* **Oct 23, 1:11 PM**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1416).
* **Oct 23, 1:12 PM**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1416) rebased this pull request as part of a merge.
* **Oct 23, 1:13 PM**: @sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1416).

**Pull request merged**
