### PR TITLE
SW-1939 Remove v1 accession endpoints

### PR DESCRIPTION
**Pull request by sgrimm**
Now that the production web app is switched over to the v2 accessions API, we can
start to get rid of the v1 API and its implementation.

This initial change removes the v1 API endpoints that have been supplanted by v2
equivalents, and removes some code that was only referenced by the endpoints'
controller methods. Specifically, the following endpoints go away:

* `GET /api/v1/seedbank/accessions/{id}` (read accession)
* `POST /api/v1/seedbank/accessions` (create accession)
* `PUT /api/v1/seedbank/accessions/{id}` (update accession)

In addition, `POST /api/v1/seedbank/accessions/{id}/checkIn` now returns a v2
response payload instead of a v1 payload. Previously, you'd get back a v1-style
response even if you were checking in an accession you'd creeated with v2, and
you'd then have to immediately GET the v2 version.

Some of the payload classes are removed here as well, but not all of them; a
few are used in unit tests and will be removed when those tests are updated to
verify the v2 business logic instead of v1. However, they will no longer be listed
in the OpenAPI schema since they aren't referenced by any controller methods.

### CODE REVIEW

**Comment by sgrimm** [comment]
@karthikbtf I won't merge this yet. Putting it up so you can pull it and use it to clean up the FE code. I forgot to mark it as a draft, but will do that now.

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #716** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/716" target="_blank">Graphite</a>  👈
    * **PR #717** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/717" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/716?utm_source=stack-comment).

**Comment by karthikbtf** [comment]
> @karthikbtf I won't merge this yet. Putting it up so you can pull it and use it to clean up the FE code. I forgot to mark it as a draft, but will do that now.

Thanks @sgrimm I will checkout this branch and work on the FE part.

**Review by karthikbtf — APPROVED** [review]
The FE PR was merged.

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/716?utm_source=stack-comment).


Job Reference: d18o7Pxq6lSzAcztQgQ3

**Pull request merged**
