### PR TITLE
SW-4085 Rename storage_locations to sub_locations

### PR DESCRIPTION
**Pull request by sgrimm**
Early versions of Terraware used the term "storage location" to describe fridges
and freezers in a seed bank. We renamed that concept to "sub-location" in the app,
but we continued to use the old name in the code.

In preparation for allowing users to add sublocations to nurseries, not just to
seed banks, start using the new name internally in the server.

This initial change is purely an internal refactoring. No changes to the API.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1410** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1410" target="_blank">Graphite</a> 
    * **PR #1411** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1411" target="_blank">Graphite</a>  👈
      * **PR #1415** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1415" target="_blank">Graphite</a> 
        * **PR #1416** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1416" target="_blank">Graphite</a> 
      * **PR #1412** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1412" target="_blank">Graphite</a> 
        * **PR #1413** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1413" target="_blank">Graphite</a> 
          * **PR #1414** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1414" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1411?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Nice. 
Curious how we'd make the API change, support both properties until client migrates over to newer property names? I am possibly jumping the gun here.

**Comment by sgrimm** [comment]
My plan for the API change here is to support both names in payloads for a transition period, then remove the old name once all our clients have switched over. We've followed the same pattern for other payload changes in the past; it's a few extra steps but not too bad.

**Comment by sgrimm** [comment]
### Merge activity

* **Oct 23, 12:35 PM**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1411).
* **Oct 23, 12:36 PM**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1411) rebased this pull request as part of a merge.
* **Oct 23, 12:37 PM**: @sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1411).

**Pull request merged**
