### PR TITLE
Increase Kotlin compiler memory

### PR DESCRIPTION
**Pull request by sgrimm**
The current compiler memory limit is just barely enough on ARM systems; upcoming
changes that added more code were causing it to run out of memory. Increase its
maximum heap size.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1299** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1299" target="_blank">Graphite</a>  👈
    * **PR #1300** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1300" target="_blank">Graphite</a> 
      * **PR #1301** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1301" target="_blank">Graphite</a> 
        * **PR #1302** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1302" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1299?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
🎉

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1299).

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1299).

**Pull request merged**
