### PR TITLE
SW-5662 Implement non-variable pre-screen checks

### PR DESCRIPTION
**Pull request by sgrimm**
Change the response of the "submit application" API endpoint to return a list of
problems and an updated copy of the application data, including its updated
status.

Implement the check logic for all the pre-screen requirements that don't involve
fetching values from variables; the variable-based ones will require the
variables to be defined which isn't done yet. But these initial checks should be
enough to support testing the submission logic in the frontend.

### CODE REVIEW

**Comment by sgrimm** [comment]
* **#2179** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2179?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2178** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2178?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2177** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2177?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgrimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sgrimm** [comment]
Picked the wrong names for the strings for some reason; will rename them and update this.

**Review by nickgraz — APPROVED** [review]
Looks great

**Comment by sgrimm** [comment]
### Merge activity

* **Jul 22, 9:19 AM EDT**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/2177).
* **Jul 22, 9:20 AM EDT**: @sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/2177).

**Pull request merged**
