### PR TITLE
SW-1054 Support localhost HTTP redirects

### PR DESCRIPTION
**Pull request by sgrimm**
Attempt to fix the problem with the login flow that prevented us from pointing
local web app dev environments at the staging or production server instances.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #851** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/851" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/851?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Tested this by setting up a local terraware-server instance to listen for HTTPS requests using a different hostname, and setting the FE dev environment to proxy to that. I believe my setup should have been an adequate simulation of staging, but I didn't run behind an AWS load balancer so there may be other subtleties.

**Review by karthikbtf — APPROVED** [review]
Thanks for doing this.
Should we disallow this on production?

**Comment by sgrimm** [comment]
The original request was to let people use this to try to reproduce FE bugs in either staging or prod, so I think we have to allow it in both.

**Comment by sgrimm** [comment]
From a security point of view it doesn't hurt to allow it in prod; it's already the case that anyone with a valid login session can call any of our API endpoints with whatever arguments they want.

**Comment by sgrimm** [comment]
Sadly, this didn't work on staging, so clearly my local setup wasn't close enough to the real thing. It gets one step closer than before but still generates a bogus redirect URL.

**Pull request merged**
