### PR TITLE
SW-1895 Add endpoint to read seedling batches

### PR DESCRIPTION
**Pull request by sgrimm**
Add the `GET /api/v1/nursery/batches/{id}` endpoint to retrieve a batch's data.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #674** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/674" target="_blank">Graphite</a> 
    * **PR #675** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/675" target="_blank">Graphite</a> 
      * **PR #676** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/676" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/676?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #674** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/674" target="_blank">Graphite</a> 
    * **PR #675** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/675" target="_blank">Graphite</a> 
      * **PR #676** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/676" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/676?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
👍

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/676?utm_source=stack-comment).


Job Reference: WhpDUt6kORcaTLYUaLHI

**Pull request merged**
