### PR TITLE
SW-4834 Support creating detailed sites via API

### PR DESCRIPTION
**Pull request by sgrimm**
`POST /api/v1/tracking/sites` now accepts optional planting zone and subzone 
definitions and will create a detailed planting site if they're present.

Detailed planting sites must obey all the same constraints (minimum areas,
unique names, etc.) that already apply to shapefile upload. In this initial
version, the API doesn't have a mechanism for communicating detailed validation
failure messages back to the client; that will be added later.

### CODE REVIEW

**Comment by sgrimm** [comment]
* **#1686** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1686?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1912** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1912?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1911** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1911?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgrimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by karthikbtf — APPROVED** [review]
Looks good to me, will the `dry run` param be added later or better to add now?

**Review by nickgraz — APPROVED** [review]
Looks good to me

**Comment by sgrimm** [comment]
### Merge activity

* **May 1, 6:04 PM EDT**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1686).
* **May 1, 6:10 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1686) couldn't merge this pull request because a downstack PR #1912 failed to merge.
* **May 1, 6:32 PM EDT**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1686).
* **May 1, 6:33 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1686) rebased this pull request as part of a merge.

**Pull request merged**
