### PR TITLE
SW-2188 Add planting sites to search API

### PR DESCRIPTION
**Pull request by sgrimm**
To support the usual filtering and sorting operations on the list of planting
sites, add them to the search API.

The `boundary` values are returned as strings whose values are JSON objects
in GeoJSON format, suitable for passing verbatim to mapping services that expect
GeoJSON values.

See `TrackingSearchTest` for an example of the field hierarchy.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #783** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/783" target="_blank">Graphite</a> 
    * **PR #784** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/784" target="_blank">Graphite</a> 
      * **PR #785** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/785" target="_blank">Graphite</a> 
        * **PR #787** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/787" target="_blank">Graphite</a>  👈
          * **PR #788** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/788" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/787?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #783** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/783" target="_blank">Graphite</a> 
    * **PR #784** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/784" target="_blank">Graphite</a> 
      * **PR #785** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/785" target="_blank">Graphite</a> 
        * **PR #787** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/787" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/787?utm_source=stack-comment).

**Comment by karthikbtf** [comment]
> Looks good to me. Something I realized a bit late, UI will need the bbox of the planting site boundary - in order to fit the map to. Not sure what the best approach would be here, should the UI calculate bbox or get help from the BE. Could get complex depending on number of polygons associated with the boundary. Just thinking aloud at this point, ok for us to make an additional request later if needed?

I take that back, the number of polygons won't complicate the bbox calculation.

**Comment by sgrimm** [comment]
The site boundary can be queried as needed here by including the `boundary` search field. It'll also be returned by the GET endpoints in the PR I just created. Hopefully that covers the UI's needs.

**Comment by karthikbtf** [comment]
> The site boundary can be queried as needed here by including the `boundary` search field. It'll also be returned by the GET endpoints in the PR I just created. Hopefully that covers the UI's needs.

@sgrimm would it be possible to provide an example of a search response with a boundary (as might be seen by the client)?

**Comment by sgrimm** [comment]
Sure. I'll put it in the Jira task so it's easier to find later on.

**Pull request merged**
