### PR TITLE
Refactor date-based observation queries

### PR DESCRIPTION
**Pull request by sgrimm**
Refactor two query methods in `ObservationStore` that get a list of observations
that's filtered based on what the current date is in the planting sites' time
zones. No change in behavior here; this is in preparation for adding a third query
that does something similar.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1211** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1211" target="_blank">Graphite</a>  👈
    * **PR #1212** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1212" target="_blank">Graphite</a> 
      * **PR #1213** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1213" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1211?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
Makes sense

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1211).

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1211).

**Pull request merged**
