### PR TITLE
Add smoke test for JobRunr API

### PR DESCRIPTION
**Pull request by sgrimm**
Twice now, we've run into Kotlin version upgrades that broke JobRunr's "extract
the parameters from the body of a lambda function" logic, but since our test suite
was always stubbing out JobRunr, we only discovered the problem at runtime.

Add a simple sanity-check test to try to detect future incidents before they get
merged.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #667** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/667" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/667?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Tested this by setting the Kotlin version to 1.7.20 locally; it fails with the same exception we were seeing in staging earlier today.

**Review by karthikbtf — APPROVED** [review]
👍 
a `.DS_Store` file got picked up

**Comment by sgrimm** [comment]
Ah, right, though it's deleted here, not added. Could split that out into a separate PR but doesn't seem worth the bother.

**Pull request merged**
