### PR TITLE
SW-4348 Remove storage locations from API

### PR DESCRIPTION
**Pull request by sgrimm**
Get rid of the endpionts and payload fields that referred to sub-locations as
"storage locations."

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1426** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1426" target="_blank">Graphite</a> 
    * **PR #1427** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1427" target="_blank">Graphite</a> 
      * **PR #1430** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1430" target="_blank">Graphite</a> 
        * **PR #1431** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1431" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1431?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1426** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1426" target="_blank">Graphite</a> 
    * **PR #1427** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1427" target="_blank">Graphite</a> 
      * **PR #1430** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1430" target="_blank">Graphite</a> 
        * **PR #1431** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1431" target="_blank">Graphite</a>  👈
      * **PR #1428** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1428" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1431?utm_source=stack-comment).

**Comment by sgrimm** [comment]
This is marked as a draft because it shouldn't be merged until after the client code has switched over to the new fields and the updated client has been released.

**Comment by sgrimm** [comment]
This is ready to review but will wait until after the next frontend production release (which removes uses of the old endpoints/fields) before merging it.

**Review by karthikbtf — APPROVED** [review]
Nice!

**Pull request merged**
