### PR TITLE
Alphabetize entries in some source files

### PR DESCRIPTION
**Pull request by sgrimm**
We have a handful of source files that have lists of tables or methods that aren't
trivially short but make sense to keep grouped together. They weren't ordered in a
way that made them easy to navigate or that made it obvious exactly where to add
new entries. Update them to sort the relevant parts alphabetically.

No functional changes here, just shuffling of names.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #546** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/546" target="_blank">Graphite</a> 
    * **PR #547** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/547" target="_blank">Graphite</a> 
      * **PR #548** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/548" target="_blank">Graphite</a> 
        * **PR #549** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/549" target="_blank">Graphite</a> 
          * **PR #550** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/550" target="_blank">Graphite</a> 
            * **PR #551** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/551" target="_blank">Graphite</a> 
              * **PR #552** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/552" target="_blank">Graphite</a> 
                * **PR #553** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/553" target="_blank">Graphite</a> 
                  * **PR #555** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/555" target="_blank">Graphite</a> 
                    * **PR #556** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/556" target="_blank">Graphite</a>  👈
                      * **PR #557** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/557" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/556?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Thanks for the cleanup.

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ⚠️ Downstack blocker

A downstack pull request blocked this pull request from being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/556?utm_source=stack-comment).


Job Reference: xGqpbvjWJBhk791ZI7p8

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/556?utm_source=stack-comment).


Job Reference: cjUYbgw8NcVK1ZvvabkK

**Pull request merged**
