### PR TITLE
Drop per-accession species details

### PR DESCRIPTION
**Pull request by sgrimm**
In the initial version of the seed bank web app, we didn't have a concept of a
"species" per se; we just had some accession fields to hold information about the
seeds' species.

We have since moved over to a centrally-managed species list. The per-accession
species details are no longer referenced anywhere, so we can drop them from the
database and the API.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #630** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/630" target="_blank">Graphite</a> 
    * **PR #631** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/631" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/631?utm_source=stack-comment).

**Comment by sgrimm** [comment]
As a sanity check, I ran with this change and did `yarn generate-types && yarn ts` in the terraware-web repo. The TypeScript check reports one error, but it's an existing one, not related to the fields I'm removing here.

**Comment by karthikbtf** [comment]
> As a sanity check, I ran with this change and did `yarn generate-types && yarn ts` in the terraware-web repo. The TypeScript check reports one error, but it's an existing one, not related to the fields I'm removing here.

`yarn ts` should be clean on `/main` - can you share the output observed by you?

**Comment by karthikbtf** [comment]
> > As a sanity check, I ran with this change and did `yarn generate-types && yarn ts` in the terraware-web repo. The TypeScript check reports one error, but it's an existing one, not related to the fields I'm removing here.
> 
> `yarn ts` should be clean on `/main` - can you share the output observed by you?

oh unless it's the renamed property for `viabilityPercent` in which case both @constanzauanini and I have PRs out with updated types.

**Review by karthikbtf — APPROVED** [review]

**Comment by sgrimm** [comment]
It's the rename of `testingStaffUserId` to `withdrawnByUserId` from commit 1a9190bc.
```
src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx:150:75 - error TS2339: Property 'testingStaffUserId' does not exist on type '{ endDate?: string | undefined; notes?: string | undefined; seedsTested?: number | undefined; seedType?: "Fresh" | "Stored" | undefined; startDate?: string | undefined; substrate?: "Other" | ... 8 more ... | undefined; testResults?: { ...; }[] | undefined; testType?: "Nursery" | ... 2 more ... | undefined; treatment...'.

150             selectedValue={users?.find((userSel) => userSel.id === record.testingStaffUserId)}
```

**Comment by karthikbtf** [comment]
> It's the rename of `testingStaffUserId` to `withdrawnByUserId` from commit [1a9190b](https://github.com/terraware/terraware-server/commit/1a9190bc1672f422e9218495a5bc9b8aa211c1e5).
> 
> ```
> src/components/accession2/viabilityTesting/NewViabilityTestModal.tsx:150:75 - error TS2339: Property 'testingStaffUserId' does not exist on type '{ endDate?: string | undefined; notes?: string | undefined; seedsTested?: number | undefined; seedType?: "Fresh" | "Stored" | undefined; startDate?: string | undefined; substrate?: "Other" | ... 8 more ... | undefined; testResults?: { ...; }[] | undefined; testType?: "Nursery" | ... 2 more ... | undefined; treatment...'.
> 
> 150             selectedValue={users?.find((userSel) => userSel.id === record.testingStaffUserId)}
> ```

Ah yes, we have PRs out for this. Thanks.

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/631?utm_source=stack-comment).


Job Reference: AY6TDCXGXTR6yclJtp7E

**Pull request merged**
