### PR TITLE
SW-5005 Added projectId for a nursery transfer

### PR DESCRIPTION
**Pull request by tommylau523**

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#1789** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1789?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sgrimm — COMMENTED** [review]
Seems reasonable, but agreed that test coverage (even if just adding a project ID to one of the existing tests) would be good to keep us from breaking this in the future.

**Review by sgrimm — CHANGES_REQUESTED** [review]
Oops, forgot to hit "Request changes" with my previous review.

**Review by sgrimm — APPROVED** [review]
Nice!

**Comment by tommylau523** [comment]
### Merge activity

* **Mar 21, 2:16 PM EDT**: @tommylau523 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1789).
* **Mar 21, 2:16 PM EDT**: @tommylau523 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1789).

**Pull request merged**
