### PR TITLE
Rename finishedPlantingTime to plantingCompletedTime

### PR DESCRIPTION
**Pull request by sgrimm**
We decided to use the terms "completed planting" and "planting completed" instead
of "finished planting" in the product. Rename the representation of this concept
in the database and the API to match the terminology in the product.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1203** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1203" target="_blank">Graphite</a> 
    * **PR #1205** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1205" target="_blank">Graphite</a> 
      * **PR #1206** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1206" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1206?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1206).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1206) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1206).

**Pull request merged**
