### PR TITLE
SW-3931 Add project IDs to entities

### PR DESCRIPTION
**Pull request by sgrimm**
Add `projectId` fields to the API payloads for accessions, seedling batches,
and planting sites.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1299** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1299" target="_blank">Graphite</a> 
    * **PR #1300** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1300" target="_blank">Graphite</a> 
      * **PR #1301** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1301" target="_blank">Graphite</a> 
        * **PR #1302** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1302" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1302?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
Looks good to me!

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1302).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1302) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1302).

**Pull request merged**
