### PR TITLE
SW-1388 Add accession search summary endpoint

### PR DESCRIPTION
**Pull request by sgrimm**
Add a new `POST /api/v1/seedbank/summary` endpoint that takes a payload with
search criteria in the same format as `/api/v1/search`. It returns a summary of
data about the accessions that match the search. The summary covers the entire
set of search results (no pagination).

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #558** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/558" target="_blank">Graphite</a> 
    * **PR #559** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/559" target="_blank">Graphite</a> 
      * **PR #560** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/560" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/560?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Looks good.

**Comment by karthikbtf** [comment]
@sgrimm the squash/merge is showing summary from previous PR (search function), do we need som graphite update?

**Comment by sgrimm** [comment]
Yes, this is GitHub being dumb about reparenting PRs. I'll take care of merging it.

**Pull request merged**
