### PR TITLE
SW-1199 Remove projects and sites from API

### PR DESCRIPTION
**Pull request by sgrimm**
Remove all the API endpoints that list and manage projects and sites. Remove
the `projects` field from the organization details payload, as well as the
database queries that populated it.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #472** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/472" target="_blank">Graphite</a> 
    * **PR #473** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/473" target="_blank">Graphite</a> 
      * **PR #474** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/474" target="_blank">Graphite</a>  👈
        * **PR #475** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/475" target="_blank">Graphite</a> 
          * **PR #476** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/476" target="_blank">Graphite</a> 
            * **PR #477** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/477" target="_blank">Graphite</a> 
              * **PR #478** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/478" target="_blank">Graphite</a> 
                * **PR #479** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/479" target="_blank">Graphite</a> 
                  * **PR #480** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/480" target="_blank">Graphite</a> 
                    * **PR #481** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/481" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/474?utm_source=stack-comment).

**Comment by karthikbtf** [comment]
@sgrimm can we wait for https://github.com/terraware/terraware-web/pull/350 to land before we attempt this one? Might break the UI in staging otherwise.

**Comment by sgrimm** [comment]
> can we wait for [terraware/terraware-web#350](https://github.com/terraware/terraware-web/pull/350) to land before we attempt this one? Might break the UI in staging otherwise.

Definitely! I will wait for the client work to finish before merging this stack.

**Comment by karthikbtf** [comment]
> > can we wait for [terraware/terraware-web#350](https://github.com/terraware/terraware-web/pull/350) to land before we attempt this one? Might break the UI in staging otherwise.
> 
> Definitely! I will wait for the client work to finish before merging this stack.

Thanks,  I will update here once ready.

**Comment by karthikbtf** [comment]
> > > can we wait for [terraware/terraware-web#350](https://github.com/terraware/terraware-web/pull/350) to land before we attempt this one? Might break the UI in staging otherwise.
> > 
> > 
> > Definitely! I will wait for the client work to finish before merging this stack.
> 
> Thanks, I will update here once ready.

This should be good to land now (for staging). The UI change has been committed.

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/474?utm_source=stack-comment).


Job Reference: RUImGER463sfWa3c6rnM

**Pull request merged**
