### PR TITLE
SW-5187 Add valid user-supplied withdrawal purposes

### PR DESCRIPTION
**Pull request by sgrimm**
In preparation for adding a new withdrawal purpose for undoing previous
withdrawals, update the "create withdrawal" endpoint to use its own list of
valid withdrawal purposes.

When the new purpose is added, it will appear in the `WithdrawalPurpose`
enum, but with this change it won't be listed as a valid user-supplied
purpose for withdrawal creation in the OpenAPI schema.

### CODE REVIEW

**Comment by sgrimm** [comment]
* **#1848** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1848?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1847** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1847?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1846** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1846?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1845** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1845?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1844** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1844?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1843** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1843?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1842** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1842?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1841** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1841?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgrimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by tommylau523 — APPROVED** [review]
I am curious. What is the purpose of this change instead of using WithdrawalPurpose directly?

**Comment by sgrimm** [comment]
In isolation, adding this enum doesn't change anything. But it will have an effect once the rest of the PRs in the stack are merged.

Using WithdrawalPurpose directly means that all the values of the enum show up in the OpenAPI schema as valid values for the field in the request payload for withdrawal creation. But "Undo" won't be a valid user-supplied withdrawal purpose; you'll use a separate endpoint to create undo withdrawals.

This new enum is how we document and enforce that "Undo" isn't accepted as a valid withdrawal purpose when creating withdrawals. But we still use WithdrawalPurpose directly in the response payloads because undo withdrawals (created by the dedicated endpoint) can be fetched.

**Comment by sgrimm** [comment]
### Merge activity

* **Apr 15, 10:16 AM EDT**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1841).
* **Apr 15, 10:17 AM EDT**: @sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1841).

**Pull request merged**
