### PR TITLE
SW-3731 Track plantings since last observation

### PR DESCRIPTION
**Pull request by sgrimm**
Replace the `planting_site_populations` and `planting_subzone_populations` views
with tables that are updated when there are outplanting nursery withdrawals, and
add an analogous table for zone-level totals.

In addition to the all-time totals, these tables also have a new column that
tracks the number of plants added since the last observation. This number
is also adjusted when there are outplanting nursery withdrawals, but is reset to
zero when an observation is completed.

Tracking these numbers explicitly will reduce the cost of the queries to populate
the plants dashboard, especially once we add the "plants planted since last
observation" stat.

Once this code is deployed, a followup migration will backfill the values for
existing planting sites. The backfill needs to happen separately to avoid the case
where an outplanting withdrawal happens while this code is in the middle of being
deployed, and happens to be handled by a previous release which would fail to
update the numbers.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1197** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1197" target="_blank">Graphite</a>  👈
    * **PR #1198** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1198" target="_blank">Graphite</a> 
      * **PR #1199** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1199" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1197?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Just curious, what's the application of plantings since last observation?
Code seems clear to me.

**Comment by sgrimm** [comment]
It's to support the bit at the bottom of this:

Screenshot 2023-06-08 at 3 15 57 PM

**Comment by karthikbtf** [comment]
> It's to support the bit at the bottom of this:
> 
> Screenshot 2023-06-08 at 3 15 57 PM

Thanks 👍 oh yes, we have all those plants dashboard changes to do.

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1197).

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1197).

**Pull request merged**
