### PR TITLE
Updated Votes API to not include project IDs in payloads

### PR DESCRIPTION
**Pull request by tommylau523**
projectId is already in the path of the API.

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#1774** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1774?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sgrimm — COMMENTED** [review]
What's the motivation here? The PR description says what the change does, but not why.

Generally we return IDs and let the clients look up further information using those IDs as needed; in a lot of cases the clients will already have the information on hand anyway. We can return names alongside the IDs as an optimization if there are going to be lots of IDs that clients aren't likely to have already looked up, but for things like turning the names into clickable links, the IDs are usually still needed.

Is there a particular reason we definitely _don't_ want to know the project IDs, just the names?

**Comment by tommylau523** [comment]
One nit thing is that projectId is already in the request path. We are returning duplicated information here. Another thing is that an accelerator admin with global roles may not have access to project names via APIs. Let's move this second point to Slack to discuss.

**Review by sgrimm — APPROVED** [review]
Makes sense.

**Pull request merged**
