### PR TITLE
SW-1939 Remove accession v2->v1 conversion code

### PR DESCRIPTION
**Pull request by sgrimm**
With the removal of the v1 API endpoints, there is no longer any way for a client
to ask the server to convert a v2-style accession to v1-style. Remove the
conversion code and its associated tests.

The v1->v2 conversion code is unaffected here; we'll continue to need it until all
existing accessions have been converted to v2.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #716** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/716" target="_blank">Graphite</a> 
    * **PR #717** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/717" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/717?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
🎉

**Review by charlie-tf — APPROVED** [review]
nice!

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/717?utm_source=stack-comment).


Job Reference: d18o7Pxq6lSzAcztQgQ3

**Pull request merged**
