### PR TITLE
Start migration subdirectories at multiples of 50

### PR DESCRIPTION
**Pull request by sgrimm**
Make the database migration subdirectories start at multiples of 50 rather than at
multiples of 50 plus one. It's a little more intuitive if, e.g., migration 100 is
in the same directory as migration 101.

No changes to the contents of any migrations here, just renaming the directories
and moving the multiple-of-50-numbered migrations to their new homes.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1197** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1197" target="_blank">Graphite</a> 
    * **PR #1198** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1198" target="_blank">Graphite</a>  👈
      * **PR #1199** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1199" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1198?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Good 👍

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1198).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1198) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1198).

**Pull request merged**
