### PR TITLE
SW-1335 Remove per-accession viability test types

### PR DESCRIPTION
**Pull request by sgrimm**
The web app no longer requires users to enable and disable different types of
viability tests, so there's no longer any need for the server to store the
list of selected test types for each accession.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #527** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/527" target="_blank">Graphite</a> 
    * **PR #528** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/528" target="_blank">Graphite</a>  👈
      * **PR #529** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/529" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/528?utm_source=stack-comment).

**Comment by sgrimm** [comment]
This shouldn't be merged until after the next FE production release.

**Review by karthikbtf — APPROVED** [review]
👍

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/528?utm_source=stack-comment).


Job Reference: I5iKiK2k4z2BqX6fGLr8

**Pull request merged**
