### PR TITLE
Stop supporting huge shapefiles

### PR DESCRIPTION
**Pull request by sgrimm**
Initially, we were going to include monitoring plot boundaries in uploaded
shapefiles for planting sites. Since there can be many thousands of monitoring
plots at a large site, this caused the shapefiles to be large enough that we
needed to stream their data in the application code rather than letting Spring
and Tomcat load them into memory or store them on disk.

But now we generate monitoring plot boundaries programmatically, and the
shapefiles are far smaller. So we can process them using the built-in file
upload support in Spring MVC. This is not only simpler, but avoids using an
API that's no longer supported in Spring Boot 3.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1247** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1247" target="_blank">Graphite</a>  👈
    * **PR #1248** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1248" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1247?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
Makes sense

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1247).

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1247).

**Pull request merged**
