### PR TITLE
SW-1365 Rename founderId to plantId in v2 accession API

### PR DESCRIPTION
**Pull request by sgrimm**
In v1, we used the term "founder ID" to refer to an externally-issued identifier
for an individual specimen of an endangered plant species. We're switching to the
term "plant ID" in the v2 user interface. Update the API to match the new
terminology, and add the field to the search API using its new name.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #659** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/659" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/659?utm_source=stack-comment).

**Comment by sgrimm** [comment]
This is a (slightly) breaking change; I didn't add a backward-compatibility alias for this new name since we haven't released any v2 clients to the world yet. The old field name will be ignored on input.

**Review by karthikbtf — APPROVED** [review]
Lgtm.

**Comment by karthikbtf** [comment]
Do we need corresponding tickets for FE and Mobile-app?

**Comment by sgrimm** [comment]
We already have them: SW-1366 and SW-1367

**Comment by sgrimm** [comment]
Holding off merging this until we get confirmation from the product team that it's okay to briefly break the mobile app before release (see discussion in Slack).

**Pull request merged**
