### PR TITLE
Remove facility scope from seedbank search API

### PR DESCRIPTION
**Pull request by sgrimm**
`/api/v1/seedbank/values/all` supports listing the values for an organization or a
facility, but we no longer ever use the facility scope. Replace the scoping
implementation with a simpler one that only supports organizations.

The fact that organization ID is a required field in the request payload is now
part of the OpenAPI schema instead of a runtime check.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1171** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1171" target="_blank">Graphite</a> 
    * **PR #1172** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1172" target="_blank">Graphite</a> 
      * **PR #1173** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1173" target="_blank">Graphite</a> 
        * **PR #1174** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1174" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1174?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Thanks for the cleanup and simplification, looks much nicer 🎉

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1174).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1174) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1174).

**Pull request merged**
