### PR TITLE
SW-5230 Convert shapefile coordinates to long/lat

### PR DESCRIPTION
**Pull request by sgrimm**
We always use the WGS 84 (longitude/latitude) coordinate system when storing
planting site geometries in the database. Currently, that conversion is done at
write time using PostGIS's coordinate transformation functions; our
`GeometryBinding` class wraps geometry values in the appropriate functions when
it generates SQL for write operations.

The downside of this is that it means when we are doing geometry calculations
on a shapefile at import time, we're potentially using a different coordinate
system than what will end up in the database. That's not a problem with the
existing write-once model, but when we support updating maps, it'll make it
more difficult to compare the old and new maps.

Update the shapefile importer to do the coordinate system transformation in the
application code before doing its geometry calculations.

The coordinate system transformation involves floating-point calculations that
can introduce slight discrepancies in boundaries; this isn't noticeable on
actual maps but caused failures in tests that were checking for strict overlap
of geometries. Change those tests to allow a slight fuzz factor like we already
allow in the application code.

### CODE REVIEW

**Comment by sgrimm** [comment]
* **#1910** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1910?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1909** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1909?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1908** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1908?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1907** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1907?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1904** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1904?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1903** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1903?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1902** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1902?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgrimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by tommylau523 — APPROVED** [review]
Nice! I had too look up a few things to do with JTS, CRS and UTM. Easy to follow afterwards!

**Review by nickgraz — APPROVED** [review]
Nice!

**Comment by sgrimm** [comment]
### Merge activity

* **Apr 30, 2:15 PM EDT**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1903).
* **Apr 30, 2:16 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1903) rebased this pull request as part of a merge.
* **Apr 30, 2:25 PM EDT**: @sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1903).

**Pull request merged**
