### PR TITLE
SW-2323 Add permissions for access to deliveries, plantings

### PR DESCRIPTION
**Pull request by sgrimm**

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #820** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/820" target="_blank">Graphite</a>  👈
    * **PR #821** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/821" target="_blank">Graphite</a> 
      * **PR #822** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/822" target="_blank">Graphite</a> 
        * **PR #823** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/823" target="_blank">Graphite</a> 
          * **PR #824** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/824" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/820?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Oops, messed up when I was breaking this change out into separate PRs (an exception class referenced here doesn't get defined until the next PR in the stack). Will fix.

**Review by karthikbtf — APPROVED** [review]
👍

**Comment by sgrimm** [comment]
Requesting a fresh look because I added a "can read planting" permission here based on feedback on the next PR in this stack.

**Review by karthikbtf — APPROVED** [review]
Thanks for the changes.

**Pull request merged**
