### PR TITLE
Generate code documentation

### PR DESCRIPTION
**Pull request by sgrimm**
Add the Dokka plugin to generate HTML documentation from our code's
class and method doc blocks. Include the Mermaid module so we can put
diagrams in our docs as well.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #971** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/971" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/971?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
Cool. Will we be committing these docs? To `main` or some other branch?

**Comment by sgrimm** [comment]
They'll be committed to the `gh-docs` branch so they show up on https://terraware.github.io/terraware-server/ (the `docs.yaml` workflow takes care of that).

**Comment by sgrimm** [comment]
Err, I mean the `gh-pages` branch.

**Pull request merged**
