### PR TITLE
SW-4329 Add facility numbers to existing identifiers

### PR DESCRIPTION
**Pull request by sgrimm**
Update the human-readable identifiers of accessions and batches to use the new
numbering scheme that includes the facility number.

Accessions with custom numbers from CSV uploads aren't updated, just ones whose
accession numbers match the old format.

DEPLOYMENT NOTE:

This should be deployed only after the code change to start generating new-style
identifiers has been deployed, so as to avoid any old identifiers slipping through
the cracks during deployment.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1426** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1426" target="_blank">Graphite</a> 
    * **PR #1427** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1427" target="_blank">Graphite</a>  👈
      * **PR #1430** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1430" target="_blank">Graphite</a> 
        * **PR #1431** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1431" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1427?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
Nice! On your deployment note, does that mean that we need to deploy [`07380cf`](https://github.com/terraware/terraware-server/pull/1426/commits/07380cf2c830115eef2c9ba5c3ab6464b1c28644) to production separately, before this commit, or can they both be part of the same release to prod (tag)?

**Comment by sgrimm** [comment]
> On your deployment note, does that mean that we need to deploy 07380cf to production separately, before this commit, or can they both be part of the same release to prod (tag)?

They should be deployed separately. Otherwise there's the possibility that during deployment, one of the server instances will still be running the old code and will create an identifier with the old format after this migration has already run on another instance, and that identifier will never be converted.

**Comment by sgrimm** [comment]
### Merge activity

* **Oct 25, 4:33 PM**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1427).
* **Oct 25, 4:33 PM**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1427) rebased this pull request as part of a merge.
* **Oct 25, 4:34 PM**: @sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1427).

**Pull request merged**
