### PR TITLE
SW-4911 Create schema for accelerator tables

### PR DESCRIPTION
**Pull request by sgrimm**
We'll shortly be creating a number of new tables for accelerator workflow data,
and there will be enough of them that they'll clutter up the `public` schema
significantly. Create a new `accelerator` schema and move the existing
accelerator-related tables there.

This is purely for the sake of keeping the data model better organized; there's
no change in behavior here.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* **#1693** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1693?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1693?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Open to feedback about the name here. I went with `accelerator` for clarity, but I admit it's long enough to be mildly annoying to type when you're writing SQL by hand. I considered `accel` but it seemed like the loss of clarity/discoverability wasn't worth the saved keystrokes.

**Comment by karthikbtf** [comment]
> Open to feedback about the name here. I went with `accelerator` for clarity, but I admit it's long enough to be mildly annoying to type when you're writing SQL by hand. I considered `accel` but it seemed like the loss of clarity/discoverability wasn't worth the saved keystrokes.

Clarity for the win. +1 for accelerator. Also helps set a guideline, next time we have another long schema name.

**Review by karthikbtf — APPROVED** [review]
Looks good to me.

**Pull request merged**
