### PR TITLE
Implemented default voters controller

### PR DESCRIPTION
**Pull request by tommylau523**
Added default voters API endpoints in `/api/v1/accelerator/voters`

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#1781** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1781?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1780** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1780?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1772** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1772?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sgrimm — COMMENTED** [review]
I'm not sure we need this. If we only expose the default voters list via the admin UI, nothing will consume these endpoints, right?

**Comment by tommylau523** [comment]
> I'm not sure we need this. If we only expose the default voters list via the admin UI, nothing will consume these endpoints, right?
> 
> 

I was working with the assumptions that the admin UI will consume these APIs. Maybe that means that I have a gap of understanding of what the admin UI actually is.

**Comment by tommylau523** [comment]
> > I'm not sure we need this. If we only expose the default voters list via the admin UI, nothing will consume these endpoints, right?
> > 
> > 
> 
> I was working with the assumptions that the admin UI will consume these APIs. Maybe that means that I have a gap of understanding of what the admin UI actually is. 

Another consideration is that when we update the list of default voters, we may want to propagate those changes to existing projects and their cohort phases. That is reflected in the downstream PR.

**Pull request closed without merging**
