### PR TITLE
SW-4085 Add sub-locations to search API

### PR DESCRIPTION
**Pull request by sgrimm**
Update the search API to allow moving away from the term "storage location."

* Add `subLocation` as an alternate name for `storageLocation` in the
  accessions search table.
* Remove `storageLocationName` from the accessions search table; the web app
  wasn't using it any more anyway so it didn't serve any purpose.
* Replace `storageLocations` with `subLocations` in the facilities search
  table. Nothing is querying this at the moment.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1410** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1410" target="_blank">Graphite</a> 
    * **PR #1411** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1411" target="_blank">Graphite</a> 
      * **PR #1415** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1415" target="_blank">Graphite</a> 
        * **PR #1416** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1416" target="_blank">Graphite</a> 
      * **PR #1412** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1412" target="_blank">Graphite</a> 
        * **PR #1413** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1413" target="_blank">Graphite</a> 
          * **PR #1414** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1414" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1414?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1410** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1410" target="_blank">Graphite</a> 
    * **PR #1411** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1411" target="_blank">Graphite</a> 
      * **PR #1412** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1412" target="_blank">Graphite</a> 
        * **PR #1413** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1413" target="_blank">Graphite</a> 
          * **PR #1414** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1414" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1414?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Looks good, thanks for the double checking client usage.

**Comment by sgrimm** [comment]
### Merge activity

* **Oct 23, 12:35 PM**: @sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1414).
* **Oct 23, 12:40 PM**: [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1414) rebased this pull request as part of a merge.
* **Oct 23, 12:41 PM**: @sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1414).

**Pull request merged**
