### PR TITLE
SW-5141 Added PhraseMatch search filter type

### PR DESCRIPTION
**Pull request by tommylau523**

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#1826** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1826?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by sgrimm — CHANGES_REQUESTED** [review]
Can we get some test coverage, both to verify it works as expected and to document how it's expected to work?

**Comment by tommylau523** [comment]
> Can we get some test coverage, both to verify it works as expected and to document how it's expected to work?
> 
> 

Yes! On it!!

**Review by sgrimm — APPROVED** [review]
Nice. The tests make it very clear what's supposed to happen.

**Comment by tommylau523** [comment]
> Nice. The tests make it very clear what's supposed to happen.
> 
> 

Thanks! I will try to spend some time this week catching up with testing on SearchService. Will try to catch up on coverages!

**Comment by sgrimm** [comment]
The search code is actually covered _fairly_ well so far, but the tests are in the seedbank and nursery packages:

* https://github.com/terraware/terraware-server/tree/main/src/test/kotlin/com/terraformation/backend/seedbank/search
* https://github.com/terraware/terraware-server/blob/main/src/test/kotlin/com/terraformation/backend/nursery/NurserySearchTest.kt

**Comment by sgrimm** [comment]
There is some overlap between the tests there and your new test but I think grouping things the way you did makes good logical sense.

**Pull request merged**
