### PR TITLE
SW-3127 IUCN conservation category in species CSV

### PR DESCRIPTION
**Pull request by sgrimm**
Update the species CSV importer to replace the "Endangered" column with "IUCN
Conservation Category." Unlike the other enumerated columns, it does not accept
localized values since the IUCN category codes are an international standard.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1255** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1255" target="_blank">Graphite</a> 
    * **PR #1256** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1256" target="_blank">Graphite</a> 
      * **PR #1257** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1257" target="_blank">Graphite</a> 
        * **PR #1258** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1258" target="_blank">Graphite</a> 
          * **PR #1259** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1259" target="_blank">Graphite</a> 
            * **PR #1260** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1260" target="_blank">Graphite</a>  👈
              * **PR #1261** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1261" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1260?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1255** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1255" target="_blank">Graphite</a> 
    * **PR #1256** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1256" target="_blank">Graphite</a> 
      * **PR #1257** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1257" target="_blank">Graphite</a> 
        * **PR #1258** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1258" target="_blank">Graphite</a> 
          * **PR #1259** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1259" target="_blank">Graphite</a> 
            * **PR #1260** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1260" target="_blank">Graphite</a>  👈
              * **PR #1261** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1261" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1260?utm_source=stack-comment).

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1255** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1255" target="_blank">Graphite</a> 
    * **PR #1256** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1256" target="_blank">Graphite</a> 
      * **PR #1257** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1257" target="_blank">Graphite</a> 
        * **PR #1258** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1258" target="_blank">Graphite</a> 
          * **PR #1259** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1259" target="_blank">Graphite</a> 
            * **PR #1260** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1260" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1260?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]
LGTM

**Pull request merged**
