### PR TITLE
SW-5925 Removed default values for decimal places

### PR DESCRIPTION
**Pull request by tommylau523**

### CODE REVIEW

**Comment by tommylau523** [comment]
* **#2364** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/2364?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tommylau523 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sgrimm** [comment]
Commented on the Jira task for this -- I am not convinced this is the right solution to the problem from a product behavior point of view.

**Review by sgrimm — APPROVED** [review]
Sounds like we want "unlimited decimal places" to be the default, so this change is good to go.

**Review by tommylau523 — COMMENTED** [review]
Holding off on submitting until there is a resolution on:
https://terraformation.atlassian.net/browse/SW-5925

**Pull request merged**
