### PR TITLE
SW-3932 Admin UI support for simple planting sites

### PR DESCRIPTION
**Pull request by sgrimm**
Allow creating and viewing simple planting sites from the admin UI.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1333** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1333" target="_blank">Graphite</a> 
    * **PR #1334** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1334" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1334?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Looks good to me.
I realized I never asked why the simple-site feature.

**Comment by sgrimm** [comment]
It was surprising to me too but apparently it's a pretty frequent feature request from customers to be able to see their planting sites on a map, even if the map is purely for display and doesn't tie into any of the tracking v2 features.

**Comment by karthikbtf** [comment]
> It was surprising to me too but apparently it's a pretty frequent feature request from customers to be able to see their planting sites on a map, even if the map is purely for display and doesn't tie into any of the tracking v2 features.

Thanks for the info, sounds like a nice thing to have for sure!

**Pull request merged**
