### PR TITLE
SW-1410 Add new withdrawal purposes to API

### PR DESCRIPTION
**Pull request by sgrimm**
As a first step in transitioning to a simplified set of withdrawal purposes, add
the new purposes to the API. A subsequent change will update all the existing
withdrawals and remove the purposes we're no longer going to support, but that
can't happen until after the client has been updated to recognize the new ones.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #546** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/546" target="_blank">Graphite</a> 
    * **PR #547** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/547" target="_blank">Graphite</a> 
      * **PR #548** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/548" target="_blank">Graphite</a> 
        * **PR #549** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/549" target="_blank">Graphite</a> 
          * **PR #550** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/550" target="_blank">Graphite</a> 
            * **PR #551** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/551" target="_blank">Graphite</a> 
              * **PR #552** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/552" target="_blank">Graphite</a> 
                * **PR #553** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/553" target="_blank">Graphite</a> 
                  * **PR #555** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/555" target="_blank">Graphite</a> 
                    * **PR #556** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/556" target="_blank">Graphite</a> 
                      * **PR #557** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/557" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/557?utm_source=stack-comment).

**Review by karthikbtf — APPROVED** [review]
Thanks. Is there a corresponding Jira for client side work? I can move it to the top of backlog.

**Comment by sgrimm** [comment]
Yeah, I made a set of tasks for this. The two client-side ones are SW-1414 and SW-1416.

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ⚠️ Downstack blocker

A downstack pull request blocked this pull request from being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/557?utm_source=stack-comment).


Job Reference: xGqpbvjWJBhk791ZI7p8

**Comment by sgrimm** [comment]
**Graphite Merge Job**

Current status: ✅ Merged

This pull request was successfully merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/557?utm_source=stack-comment).


Job Reference: cjUYbgw8NcVK1ZvvabkK

**Pull request merged**
