### PR TITLE
SW-3797 Add Spanish CSV templates

### PR DESCRIPTION
**Pull request by sgrimm**
Add Spanish versions of the accession, seedling batch, and species CSV templates.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1231** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1231" target="_blank">Graphite</a> 
    * **PR #1232** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1232" target="_blank">Graphite</a> 
      * **PR #1233** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1233" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1233?utm_source=stack-comment).

**Review by charlie-tf — APPROVED** [review]

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1233).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1233) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1233).

**Pull request merged**
