### PR TITLE
SW-3697 Add "finished planting" flag to subzones

### PR DESCRIPTION
**Pull request by sgrimm**
Allow admins to indicate that they have finished planting a planting subzone.

This doesn't do anything yet, but will affect some of the calculations we'll do
with observation data (e.g., estimating plant populations). Some of the
calculations depend on whether or not an entire planting zone is finished
planting; rather than tracking that as a user-modifiable flag, we'll instead
derive it from the subzones.

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1175** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1175" target="_blank">Graphite</a> 
    * **PR #1178** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1178" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1178?utm_source=stack-comment).

**Comment by sgrimm** [comment]
There's some inconsistency in the PRD about what this concept is called ("fully planted" or "finished planting") so I did it both ways here. I'm guessing we'll go with "fully planted" but if I'm wrong, I'll revert commit 9e89b9a.

**Comment by sgrimm** [comment]
I guessed wrong -- we want it to be called "finished planting."

**Review by karthikbtf — APPROVED** [review]
Looks good to me, easy to follow 👍

**Comment by sgrimm** [comment]
@sgrimm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1178).

**Comment by sgrimm** [comment]
[Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1178) rebased this pull request as part of a merge.

**Comment by sgrimm** [comment]
@sgrimm merged this pull request with [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1178).

**Pull request merged**
