### PR TITLE
Add batches to facility inventories

### PR DESCRIPTION
**Pull request by sgrimm**

### CODE REVIEW

**Comment by sgrimm** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1582** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1582?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/terraware/terraware-server/1582?utm_source=stack-comment).

**Comment by sgrimm** [comment]
@charlie-tf This is what I had in mind. With this change, you can add `batches.id` as a search field. For example, if you have that and `species_scientificName`, you'd get back a result like
```json
{
    "results": [
        {
            "batches": [
                { "id": "5" }
            ],
            "species_scientificName": "Ficus capreifolia"
        },
        {
            "batches": [
                { "id": "7" },
                { "id": "11" }
            ],
            "species_scientificName": "Ficus cordata"
        }
    ]
}
```

**Comment by charlie-tf** [comment]
Oh, fantastic! I was not fully aware of how this is done, and I appreciate the illustration.

**Comment by charlie-tf** [comment]
Happy to close my PR and merge this one instead if you're okay with it.

**Review by charlie-tf — APPROVED** [review]

**Pull request merged**
