### PR TITLE
SW-5118 Add cohorts and participants to search API

### PR DESCRIPTION
**Pull request by sgrimm**
Add two search tables for cohorts and participants, both only accessible to users
with appropriate global roles. They are reachable via the `participant` sublist
on the projects search table.

Example search request to return a hierarchical list of all cohorts and their
projects:

    {
      "prefix": "projects.participant.cohort",
      "fields": [
        "id",
        "name",
        "phase",
        "participants.id",
        "participants.name",
        "participants.projects.id",
        "participants.projects.name"
      ]
    }

### CODE REVIEW

**Comment by sgrimm** [comment]
* **#1809** <a href="https://app.graphite.dev/github/pr/terraware/terraware-server/1809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sgrimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by karthikbtf — APPROVED** [review]
Looks good to me 👍 
Can this be used to search projects as well (Under Overview/Projects tab)? The only additional column there is a `Restorable Land` property.

**Comment by sgrimm** [comment]
> Can this be used to search projects as well (Under Overview/Projects tab)? The only additional column there is a Restorable Land property.

@karthikbtf Commit ea7cdbc added a table for project accelerator details and you can include the fields from there with search requests. For that page, you'd probably want to flatten all the fields except land use model types (which can have multiple values) so the request would look like

```json
{   
  "prefix": "projects",
  "fields": [
    "id",
    "name",
    "participant_name",
    "participant_cohort_name",
    "participant_cohort_phase",
    "country_name",
    "country_region",
    "acceleratorDetails_confirmedReforestableLand",
    "landUseModelTypes.landUseModelType"
  ]   
}   
```

**Comment by karthikbtf** [comment]
> > Can this be used to search projects as well (Under Overview/Projects tab)? The only additional column there is a Restorable Land property.
> 
> @karthikbtf Commit [ea7cdbc](https://github.com/terraware/terraware-server/commit/ea7cdbc1988a019b34f5e54fb4d0a0ed7bdac03a) added a table for project accelerator details and you can include the fields from there with search requests. For that page, you'd probably want to flatten all the fields except land use model types (which can have multiple values) so the request would look like
> 
> ```json
> {   
>   "prefix": "projects",
>   "fields": [
>     "id",
>     "name",
>     "participant_name",
>     "participant_cohort_name",
>     "participant_cohort_phase",
>     "country_name",
>     "country_region",
>     "acceleratorDetails_confirmedReforestableLand",
>     "landUseModelTypes.landUseModelType"
>   ]   
> }   
> ```

Nice, thanks!

**Comment by karthikbtf** [comment]
> > Can this be used to search projects as well (Under Overview/Projects tab)? The only additional column there is a Restorable Land property.
> 
> @karthikbtf Commit [ea7cdbc](https://github.com/terraware/terraware-server/commit/ea7cdbc1988a019b34f5e54fb4d0a0ed7bdac03a) added a table for project accelerator details and you can include the fields from there with search requests. For that page, you'd probably want to flatten all the fields except land use model types (which can have multiple values) so the request would look like
> 
> ```json
> {   
>   "prefix": "projects",
>   "fields": [
>     "id",
>     "name",
>     "participant_name",
>     "participant_cohort_name",
>     "participant_cohort_phase",
>     "country_name",
>     "country_region",
>     "acceleratorDetails_confirmedReforestableLand",
>     "landUseModelTypes.landUseModelType"
>   ]   
> }   
> ```

I have the client filtering on presence of a `participant_cohort_id` (since we only want to show participant projects). If there's another way to do this filtering at search time I can try that, like an exists check. If the client side filtering is OK I will keep that.

**Comment by karthikbtf** [comment]
> > > Can this be used to search projects as well (Under Overview/Projects tab)? The only additional column there is a Restorable Land property.
> > 
> > 
> > @karthikbtf Commit [ea7cdbc](https://github.com/terraware/terraware-server/commit/ea7cdbc1988a019b34f5e54fb4d0a0ed7bdac03a) added a table for project accelerator details and you can include the fields from there with search requests. For that page, you'd probably want to flatten all the fields except land use model types (which can have multiple values) so the request would look like
> > ```json
> > {   
> >   "prefix": "projects",
> >   "fields": [
> >     "id",
> >     "name",
> >     "participant_name",
> >     "participant_cohort_name",
> >     "participant_cohort_phase",
> >     "country_name",
> >     "country_region",
> >     "acceleratorDetails_confirmedReforestableLand",
> >     "landUseModelTypes.landUseModelType"
> >   ]   
> > }   
> > ```
> 
> I have the client filtering on presence of a `participant_cohort_id` (since we only want to show participant projects). If there's another way to do this filtering at search time I can try that, like an exists check. If the client side filtering is OK I will keep that.

Ok looks like the client side filtering won't work for csv downloads.

**Comment by sgrimm** [comment]
You should be able to use a search criterion like

    {
      "operation": "not",
      "child": {
        "operation": "field",
        "field": "participant_cohort_id",
        "values": [null]
      }
    }

to only return projects that are in participants that are in cohorts.

**Comment by karthikbtf** [comment]
> You should be able to use a search criterion like
> 
> ```
> {
>   "operation": "not",
>   "child": {
>     "operation": "field",
>     "field": "participant_cohort_id",
>     "values": [null]
>   }
> }
> ```
> 
> to only return projects that are in participants that are in cohorts.

Thanks, this works, forgot about null values.

**Pull request merged**
